var data=require(process.cwd()+'/src/com/protractor/utility/data.json')
var homeLogin=require(process.cwd()+'/src/com/protractor//pages/HomeLoginPage.js')
var winston=require('winston')
winston.add(winston.transports.File, { filename: './Logs/XYZBankLogFile.log' })
winston.level='debug';

describe('XYZ Bank',function(){
	
	it('Bank Manager login page',function(){
		
		/* TC1: Login Page */
		browser.get(data.url);
		browser.manage().window().maximize();
		winston.log("info","Url has been launched");
		
		/* Customer Login and Bank Manager Login should present */
		
		homeLogin.verifyCustButton(data.HomeLogin.CustomerLogin);
		homeLogin.verifyBankButton(data.HomeLogin.BankManagerLogin);
		
		/* TC2: Manager Login */
		var manager=homeLogin.clickManagerLogin();
		browser.sleep(5000);
		
		/*Manager page lunched with the Options Add customer,Open accounts,Customer */
		
		manager.verifyAddCust(data.Manager.AddCustomer);
		manager.verifyOpenAccount(data.Manager.OpenAccount);
		manager.verifyCustomersButton(data.Manager.Customers);
		
		/* TC3: Add Customer */
		var addCustomer=manager.clickaddCustomer();
		browser.sleep(5000);
		var firstN=addCustomer.enterFirstName(data.AddCustomer.FirstName);
		var lastN=addCustomer.enterLastName(data.AddCustomer.LastName);
		addCustomer.enterPostCode(data.AddCustomer.PostCode);
		addCustomer.clickaddCustomer();
		
		/* Pop message will appear & says Customer added sucessfully with its autogenerated customer id*/
	
		//addCustomer.verifyAcceptAlert(data.AddCustomer.alertMessage);
		addCustomer.verifyAcceptAlert("Customer added successfully with customer id");
		browser.sleep(8000);
		
		/* TC4: To open Account for doller */
		var openAccount=addCustomer.clickOpenAccount();
		openAccount.selectCusDropDown();
		openAccount.selectCurrencyDropDown(1);
		openAccount.clickProcess();
		
		/*Pop message will appear & says Account created successfully with autogenerated account Number for doller */
		openAccount.verifyAcceptAlert("Account created successfully with account Number");
		
		/* TC5: To open Account for Pound */
	    
		openAccount.selectCusDropDown();
		openAccount.selectCurrencyDropDown(2);
		openAccount.clickProcess();

		/*Pop message will appear & says Account created successfully with autogenerated account Number for Pound */
		openAccount.verifyAcceptAlert("Account created successfully with account Number");
	
		
        /* TC6: To open Account for Rupee */
	    
		openAccount.selectCusDropDown();
		openAccount.selectCurrencyDropDown(3);
		openAccount.clickProcess();

		/*Pop message will appear & says Account created successfully with autogenerated account Number for Rupee */
		openAccount.verifyAcceptAlert("Account created successfully with account Number");
	
		
		 /* TC7: To delete customer */
	    
		var customer=openAccount.clickCustomers();
		customer.enterCustName(data.AddCustomer.FirstName);
		customer.deleteCustomer();
		
		/* Respective customer will be deleted.it stays in the customers page*/
		customer.verifyTitle("Protractor practice website - Banking App")
		
	});
	
	xit('Customer login page',function(){
		/* Login Page */
		browser.get(data.url);
		browser.manage().window().maximize();
	
		/* TC8: For Customer Login */
		var customerLogin=homeLogin.clickcustomerLogin();
		customerLogin.selectCusDropDown(1);
		
		/*Harry poter Customer login page */
		customerLogin.verifyTitle("Protractor practice website - Banking App")
		
		/* TC9: Verify Currency Type */
		var account=customerLogin.clickLoginButton();
		browser.sleep(5000);
		
		/* Verify Currency Type */
		
		account.selectAccDropDown(0)
		
		account.selectAccDropDown(1)
		
		account.selectAccDropDown(2)
		
		/* TC10: Initial Transaction */
		
		var listTX=account.clickTransactionsButton();
		
		/* Verify Transection should be empty*/
		
		listTX.verifyTransectiontable("");
		
	});	
		xit('Customer Deposit Money page',function(){
			/* Login Page */
			browser.get(data.url);
			browser.manage().window().maximize();
		
		    /*TC11: Deposit Money*/
			var customerLogin=homeLogin.clickcustomerLogin();
			customerLogin.selectCusDropDown(1);
			var account=customerLogin.clickLoginButton();
			browser.sleep(5000);
			account.selectAccDropDown(2)
			browser.sleep(5000);
			account.clickDepositTopButton()
			account.enterAmount(data.AddCustomer.Amount)
			account.clickDepositButton();
			
			/*TC12:  TransectionAfterDeposit */
			/* Balance should be 2000 for the account number 1006 */
			var listTX=account.clickTransactionsButton();
			browser.sleep(5000);
			
			/* verify latest row of data */
			listTX.verifyTransectiontable("2000 Credit");
			var account=listTX.clickBackBtn()

			/*	TC13: WithDrawError  */
			account.selectAccDropDown(2)
			browser.sleep(5000);
			account.clickWithdrawTopBtn()
			account.enterAmount(data.AddCustomer.AmountWithdrawl)
			account.clickWithdrawlButton();
			
			/* Verify error message */
			account.verifyErrorMessage("Transaction Failed. You can not withdraw amount more than the balance.")
			
			/* TC14: WithDraw Success */
			//account.enterAmount("")
			account.enterAmount(data.AddCustomer.AmountWithdrawlValid)
			//account.enterAmount(data.AddCustomer.Amount)
			account.clickWithdrawlButton();
			
			
			/* Verify success message */
			account.verifyErrorMessage("Transaction successful")
			
			/* TC15: Transection After Withdrawl */
			
			var listTX=account.clickTransactionsButton()
			browser.sleep(9000);
			
			/* Verify amount column data should have 1000 traction type column data should be Debit */
			//listTX.verifyTransectiontable("1000 Debit")
			
	});
		
		
		xit('TransectionReset',function(){
			/* Login Page */
			browser.get(data.url);
			browser.manage().window().maximize();
		    
			/* TC16: TransectionReset */
		
			var customerLogin=homeLogin.clickcustomerLogin();
			customerLogin.selectCusDropDown(1);
			var account=customerLogin.clickLoginButton();
			browser.sleep(5000);
			account.selectAccDropDown(2)
			browser.sleep(5000);
		
			var listTX=account.clickTransactionsButton()
				
			/* Transection should be empty */
			listTX.verifyTransectiontable("")
			
			/* TC17 : To go to Main Page */
			
			var account=listTX.clickBackBtn()
			
			/* TC18: To Logout */
			
			account.clickLogoutBtn()
			
	});
	
	
});

